[2024-08-19T17:22:37.322+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-19T17:22:37.341+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train.save_results manual__2024-08-19T12:21:57.618782+00:00 [queued]>
[2024-08-19T17:22:37.350+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train.save_results manual__2024-08-19T12:21:57.618782+00:00 [queued]>
[2024-08-19T17:22:37.350+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-19T17:22:37.381+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): save_results> on 2024-08-19 12:21:57.618782+00:00
[2024-08-19T17:22:37.397+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10584) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-19T17:22:37.398+0500] {standard_task_runner.py:72} INFO - Started process 10628 to run task
[2024-08-19T17:22:37.404+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train', 'save_results', 'manual__2024-08-19T12:21:57.618782+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_dag-checkpoint.py', '--cfg-path', '/tmp/tmpgx5pu9pi']
[2024-08-19T17:22:37.406+0500] {standard_task_runner.py:105} INFO - Job 29: Subtask save_results
[2024-08-19T17:22:37.501+0500] {task_command.py:467} INFO - Running <TaskInstance: train.save_results manual__2024-08-19T12:21:57.618782+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-19T17:22:37.581+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='train' AIRFLOW_CTX_TASK_ID='save_results' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T12:21:57.618782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-19T12:21:57.618782+00:00'
[2024-08-19T17:22:37.581+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-19T17:22:37.590+0500] {train_dag-checkpoint.py:168} INFO - Все посчитталось
[2024-08-19T17:22:37.590+0500] {python.py:240} INFO - Done. Returned value was: None
[2024-08-19T17:22:37.603+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-19T17:22:37.603+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=train, task_id=save_results, run_id=manual__2024-08-19T12:21:57.618782+00:00, execution_date=20240819T122157, start_date=20240819T122237, end_date=20240819T122237
[2024-08-19T17:22:37.628+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-19T17:22:37.649+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-19T17:22:37.652+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
