[2024-10-08T21:42:06.336+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T21:42:06.351+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rf_train.save_results manual__2024-10-08T16:39:13.516590+00:00 [queued]>
[2024-10-08T21:42:06.358+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rf_train.save_results manual__2024-10-08T16:39:13.516590+00:00 [queued]>
[2024-10-08T21:42:06.359+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-08T21:42:06.370+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): save_results> on 2024-10-08 16:39:13.516590+00:00
[2024-10-08T21:42:06.383+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=55581) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T21:42:06.383+0500] {standard_task_runner.py:72} INFO - Started process 55627 to run task
[2024-10-08T21:42:06.383+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rf_train', 'save_results', 'manual__2024-10-08T16:39:13.516590+00:00', '--job-id', '899', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmpy886_l2u']
[2024-10-08T21:42:06.385+0500] {standard_task_runner.py:105} INFO - Job 899: Subtask save_results
[2024-10-08T21:42:06.437+0500] {task_command.py:467} INFO - Running <TaskInstance: rf_train.save_results manual__2024-10-08T16:39:13.516590+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-08T21:42:06.518+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='rf_train' AIRFLOW_CTX_TASK_ID='save_results' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T16:39:13.516590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T16:39:13.516590+00:00'
[2024-10-08T21:42:06.519+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T21:42:06.704+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-08T21:42:06.704+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-08T21:42:12.498+0500] {train_models.py:273} INFO - Результаты сохранены в папку result
[2024-10-08T21:42:12.500+0500] {python.py:240} INFO - Done. Returned value was: None
[2024-10-08T21:42:12.511+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T21:42:12.511+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rf_train, task_id=save_results, run_id=manual__2024-10-08T16:39:13.516590+00:00, execution_date=20241008T163913, start_date=20241008T164206, end_date=20241008T164212
[2024-10-08T21:42:12.579+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-10-08T21:42:12.595+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T21:42:12.598+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
