[2024-10-08T21:30:19.516+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T21:30:19.535+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rf_train.get_data manual__2024-10-08T16:30:15.410791+00:00 [queued]>
[2024-10-08T21:30:19.542+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rf_train.get_data manual__2024-10-08T16:30:15.410791+00:00 [queued]>
[2024-10-08T21:30:19.543+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-08T21:30:19.561+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_data> on 2024-10-08 16:30:15.410791+00:00
[2024-10-08T21:30:19.573+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=44416) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T21:30:19.574+0500] {standard_task_runner.py:72} INFO - Started process 44494 to run task
[2024-10-08T21:30:19.574+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rf_train', 'get_data', 'manual__2024-10-08T16:30:15.410791+00:00', '--job-id', '866', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmpeeu3did7']
[2024-10-08T21:30:19.576+0500] {standard_task_runner.py:105} INFO - Job 866: Subtask get_data
[2024-10-08T21:30:19.629+0500] {task_command.py:467} INFO - Running <TaskInstance: rf_train.get_data manual__2024-10-08T16:30:15.410791+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-08T21:30:19.710+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='rf_train' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T16:30:15.410791+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T16:30:15.410791+00:00'
[2024-10-08T21:30:19.711+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T21:30:19.903+0500] {base.py:84} INFO - Retrieving connection 'pg_connection'
[2024-10-08T21:30:19.929+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-08T21:30:19.929+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-08T21:30:21.552+0500] {train_models.py:108} INFO - Данные загружены из б/д и сохранены на S3
[2024-10-08T21:30:21.554+0500] {python.py:240} INFO - Done. Returned value was: {'model': 'rf', 'start_timestamp': '20241008 21:30', 'experiment_id': '142', 'get_data_start': '20241008 21:30', 'get_data_end': '20241008 21:30', 'data_shape': (20640, 9)}
[2024-10-08T21:30:21.602+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T21:30:21.602+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rf_train, task_id=get_data, run_id=manual__2024-10-08T16:30:15.410791+00:00, execution_date=20241008T163015, start_date=20241008T163019, end_date=20241008T163021
[2024-10-08T21:30:21.637+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-10-08T21:30:21.663+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T21:30:21.666+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
