[2024-08-19T08:45:12.202+0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-19T08:45:12.224+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hgb_train.save_results scheduled__2024-08-18T01:00:00+00:00 [queued]>
[2024-08-19T08:45:12.232+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hgb_train.save_results scheduled__2024-08-18T01:00:00+00:00 [queued]>
[2024-08-19T08:45:12.233+0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-19T08:45:12.248+0500] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_results> on 2024-08-18 01:00:00+00:00
[2024-08-19T08:45:12.261+0500] {logging_mixin.py:188} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=37859) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-19T08:45:12.260+0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'hgb_train', 'save_results', 'scheduled__2024-08-18T01:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_models-checkpoint.py', '--cfg-path', '/tmp/tmpm96mpgky']
[2024-08-19T08:45:12.262+0500] {standard_task_runner.py:64} INFO - Started process 37911 to run task
[2024-08-19T08:45:12.262+0500] {standard_task_runner.py:91} INFO - Job 274: Subtask save_results
[2024-08-19T08:45:12.315+0500] {task_command.py:426} INFO - Running <TaskInstance: hgb_train.save_results scheduled__2024-08-18T01:00:00+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-19T08:45:12.405+0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='hgb_train' AIRFLOW_CTX_TASK_ID='save_results' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T01:00:00+00:00'
[2024-08-19T08:45:12.405+0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-19T08:45:12.439+0500] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-08-19T08:45:12.440+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-08-19T08:45:13.348+0500] {python.py:237} INFO - Done. Returned value was: None
[2024-08-19T08:45:13.349+0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-19T08:45:13.363+0500] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hgb_train, task_id=save_results, run_id=scheduled__2024-08-18T01:00:00+00:00, execution_date=20240818T010000, start_date=20240819T034512, end_date=20240819T034513
[2024-08-19T08:45:13.440+0500] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-19T08:45:13.457+0500] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-19T08:45:13.460+0500] {local_task_job_runner.py:222} INFO - ::endgroup::
